# Fix for pgadmin container:
# 1. docker-compose up
# 2. docker exec -it -u root nest_application_starter_pgadmin sh
# 3. chown -R pgadmin:pgadmin /var/lib/pgadmin

version: "3.9"
services:
  postgres:
    container_name: nest_application_starter_db
    image: postgres:13.3
    environment:
      POSTGRES_DB: "application_starter"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  postgres_test:
    container_name: nest_application_starter_db_test
    image: postgres:13.3
    environment:
      POSTGRES_DB: "application_starter_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata-test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: nest_application_starter_pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge